language: php
php:
  - '7.2'

install:
  - composer install --dev --no-interaction --no-scripts

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit
  - vendor/bin/phpcs

after_success:
  - travis_retry php vendor/bin/php-coveralls