version: '3'
services:
  app:
    build: .
    image: gitlab-time-track
    ports:
      - 80:80
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: gitlab-time-track
      DB_USER: app
      DB_PASSWORD: password
      SYMFONY_ENV: prod
      SECRET_KEY: o7AMrPAaF7yfrfstkTmdhCrtjoTjeTtd
      GITLAB_TOKEN: EnterYourSecretTokenHere
      GITLAB_SERVER_URL: https://gitlab.com/api/v4
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gitlab-time-track
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mysql

volumes:
  data: {}
