<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Project;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTimedIssuesRelatedToProject(Project $project)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT i FROM AppBundle:Issue i 
             WHERE i.project = :project 
             AND (i.timeEstimate > 0 OR i.totalTimeSpent > 0)
             ORDER BY i.gitlabId DESC'
        )->setParameter('project', $project)->getResult();
    }
}
