<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSortedByTitle($order = 'ASC')
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Project p  ORDER BY p.name $order"
            )->getResult();
    }
}
