<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSortedByTitle($order = 'ASC')
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Project p  ORDER BY p.name $order"
            )->getResult();
    }

    /**
     * Returns the number of project monitored by GitlabTimeTrack
     *
     * @return int|mixed
     */
    public function countProjects()
    {
        $qry = $this->createQueryBuilder('p')
            ->select('COUNT(p.id)')
            ->getQuery();

        try {
            $result = $qry->getSingleScalarResult();
        } catch (NoResultException $e) {
            return 0;
        }catch (NonUniqueResultException $e) {
            return 0;
        }

        return $result;
    }
}
